name:                minimilho
version:             0.1.0.0
github:              "githubuser/minimilho"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minimilho#readme>

dependencies:
- base                >= 4.7      && < 5
- parser-combinators  >= 1.3.0    && < 2.0
- containers          >= 0.6.5.1  && < 0.7
- megaparsec          >= 9.2.0    && < 10.0
- text                >= 1.2.4.1  && < 1.3
- mtl                 >= 2.2.2    && < 2.3


library:
  source-dirs: src

executables:
  minimilho-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minimilho

tests:
  minimilho-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minimilho
